GET localhost:8080/api/clients/all

###
POST http://localhost:8080/api/clients/add
Content-Type: application/json

{
  "email": "client5@gmail.com",
  "password": "password",
  "accountBalance": 400
}
###

DELETE http://localhost:8080/api/clients/delete/6

###

PUT http://localhost:8080/api/clients/withdraw/3/600

###

PUT http://localhost:8080/api/clients/deposit/1/1000